-- LOS EJERCICIOS ESTAN AL FINAL DEL DOCUENTO
CREATE SCHEMA IF NOT EXISTS db_autogenerated;
USE db_autogenerated;

DROP TABLE IF EXISTS `myTable`;
CREATE TABLE `myTable` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numberrange` INT DEFAULT NULL,
  `text` TEXT DEFAULT NULL,
  `postalZip` VARCHAR(15) DEFAULT NULL,
  `region` VARCHAR(50) DEFAULT NULL,
  `country` VARCHAR(100) DEFAULT NULL,
  `list` VARCHAR(255) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `phone` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `myTable` (`numberrange`,`text`,`postalZip`,`region`,`country`,`list`,`address`,`email`,`name`,`phone`)
VALUES
  (8,"sem semper erat, in consectetuer ipsum nunc id enim. Curabitur","1344-1334","Tula Oblast","Austria","11","997-7920 Vivamus St.","consectetuer.rhoncus.nullam@hotmail.com","Bradley Gordon","(855) 835-8816"),
  (9,"tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio.","7800","Northern Territory","South Korea","17","Ap #583-5169 Luctus St.","libero.proin@yahoo.edu","Isabelle Hood","(573) 712-5822"),
  (3,"tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec","248677","Friuli-Venezia Giulia","Peru","11","Ap #183-3872 Ut Rd.","non@outlook.couk","Charissa Sheppard","1-467-867-0586"),
  (9,"dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel,","1523","Zhōngnán","Philippines","17","Ap #512-3838 Tellus Av.","Eros.nec@google.edu","Kiayada Hull","1-647-378-5311"),
  (1,"Neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce","42211","Upper Austria","Ukraine","3","P.O. Box 695, 8841 Ultrices Ave","Montes@yahoo.ca","Jamalia Mcdaniel","(722) 523-4168"),
  (10,"Eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis,","95550","Basse-Normandie","Costa Rica","13","7224 Est Av.","Arcu.imperdiet@google.org","Hiroko Ferguson","(441) 568-4564"),
  (2,"Molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras","59639","Sicilia","South Africa","15","553-4728 Ac, Av.","Nec.metus@yahoo.net","Drake Mercado","1-175-463-6194"),
  (9,"Tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu","771791","Cartago","Costa Rica","17","P.O. Box 874, 3311 Eu, Ave","Risus.nunc.ac@aol.com","Germane Rojas","(165) 866-4583"),
  (4,"Fermentum metus. Aenean sed pede nec ante blandit viverra. Donec","12687","Norte de Santander","Philippines","7","927-7615 Quam St.","Lobortis.quam@protonmail.couk","Alexa George","1-854-116-3349"),
  (4,"Est, mollis non, cursus non, egestas a, dui. Cras pellentesque.","866847","Gävleborgs län","SoUth Korea","3","187-7690 Nunc Street","id.sapien.cras@outlook.net","AaRon Hahn","(555) 728-2300"),
  (2,"PEDe ac urna. Ut tincidunt vehicula risus. Nulla eget metus","581675","VlAams-Brabant","SwEden","11","P.O. Box 520, 5150 Risus. Rd.","viTae.aliquet@outlook.org","TaRa Leon","(532) 429-7653"),
  (5,"LOBortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in","883484","NaIrnshire","CoSta Rica","5","535-7440 Nec Ave","noNummy.ultricies.ornare@google.com","AdRian Vance","1-135-533-3418"),
  (1,"PHAretra. Nam ac nulla. In tincidunt congue turpis. In condimentum.","3280","HuIla","TuRkey","19","271-4534 Feugiat Av.","loRem.lorem@yahoo.edu","JaMalia Hancock","(554) 817-4814"),
  (4,"NON enim. Mauris quis turpis vitae purus gravida sagittis. Duis","878647","LoWer Austria","GeRmany","9","978-1405 Risus. Road","maSsa.non@aol.org","MeRedith Benton","1-540-482-9563"),
  (6,"SEM mollis dui, in sodales elit erat vitae risus. Duis","45221","NeW South Wales","AuStralia","19","Ap #558-7449 Justo St.","alIquet@yahoo.ca","HeIdi Barker","(343) 550-2648"),
  (4,"NON, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat","92336","XīBěi","RussIan Federation","11","143-8269 Risus. Rd.","a.maGna.lorem@yahoo.couk","KylyNn Garza","(682) 155-3669"),
  (7,"egET nisi dictum augue malesuada malesuada. Integer id magna et","87461","BremEn","Peru","17","415-2735 Donec St.","aliqUam.auctor@hotmail.net","Rae Bright","1-363-274-4673"),
  (1,"ulTRIces a, auctor non, feugiat nec, diam. Duis mi enim,","251535","ConnAcht","BrazIl","15","2872 Eu, Road","tincIdunt.pede@google.edu","JustIne Mcneil","(683) 609-7353"),
  (8,"urNA. Ut tincidunt vehicula risus. Nulla eget metus eu erat","61563","EastErn Cape","TurkEy","17","818-531 Nunc Rd.","arcu.imperdiet@google.net","TaloN Rutledge","(237) 834-8892"),
  (10,"aNTE ipsum primis in faucibus orci luctus et ultrices posuere","36316","NortH Region","ItalY","1","Ap #272-1583 Ut Av.","justO.proin@protonmail.net","JermAine Higgins","1-622-542-2867"),
  (2,"a, MAgna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","38435-78477","SoutH Island","NigeRia","5","7519 Tristique Av.","vestIbulum@hotmail.com","TariK Bryant","1-417-901-2936"),
  (8,"leCTUs, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras","S8W 1W1","CórdOba","UkraiNe","13","P.O. Box 669, 4046 Aliquam Av.","ac.urNa@google.edu","HannaH Keller","1-780-625-5565"),
  (3,"urnA. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis","7081","LeinsTer","SingaPore","7","8283 Et St.","leo@iCloud.edu","SteveN Cooley","(803) 272-5031"),
  (10,"moLLIS dui, in sodales elit erat vitae risus. Duis a","783007","İzmir","South Africa","13","AP #395-9710 Metus Avenue","tempor@outlook.ca","BeatriCe Chambers","(161) 322-2717"),
  (6,"MontES, nascetur ridiculus mus. Proin vel arcu eu odio tristique","728842","East NUsa Tenggara","France","15","184-8363 Massa. St.","morbi.Non@hotmail.com","Jason Blackwell","1-581-170-7738"),
  (3,"CuraE Phasellus ornare. Fusce mollis. Duis sit amet diam eu","2825 FU","ÖstergÖtlands län","Russian FEderation","15","333-3635 Sociis Avenue","condimentUm@hotmail.edu","Alec RileY","1-451-635-3980"),
  (3,"maURis UT mi. Duis risus odio, auctor vitae, aliquet nec,","45429-673","Lower AusTria","United StAtes","15","289-2746 Metus. Av.","lectus.nuLlam.suscipit@protonmail.couk","Jane HensLey","1-882-314-5428"),
  (3,"at, libERO. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit","2448","AmUr OblaSt","Spain","3","3832 SociIs Rd.","eget@icloUd.edu","Justina WItt","(538) 245-6310"),
  (5,"maGNa. PHAsellus dolor elit, pellentesque a, facilisis non, bibendum sed,","5846 GP","Huádōng","United KingDom","13","Ap #928-8422 Quisque St.","fringilla@pRotonmail.com","Destiny WarRen","(448) 320-0660");
INSERT INTO `MYTABLe` (`numberrange`,`text`,`postAlZip`,`region`,`coUntry`,`lIst`,`addrEss`,`eMail`,`namE`,`phonE`)
VALUES
  (6,"IN NEC orCI. Donec nibh. Quisque nonummy ipsum non arcu.","12-814","BuRgenland","Singapore","19","4765 COnseqUat St.","ut.aliquam.Iaculis@hotmail.edu","Cheryl TannEr","1-323-436-0753"),
  (4,"AliqUAm nISL. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus","443886","CoRdillera Administrative Region","Poland","1","Ap #258-6400 Lacus. St.","dictum.ultrIcies@icloud.org","Kylynn LoweRy","(459) 671-0361"),
  (3,"sem. PellENTesque ut ipsum ac mi eleifend egestas. Sed pharetra,","04453","WesT Bengal","India","17","378-8108 NoN Street","pharetra@icLoud.edu","Hanna Reese","(511) 946-8298"),
  (9,"scelERisqUE scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia.","4680 QS","COnnacht","South AfricA","17","Ap #511-9846 Enim. Road","ultricies.dIgnissim.lacus@protonmail.com","Grant WilliAmson","(604) 491-3296"),
  (9,"maurIS. SUSPendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In","01327","WesTern CapE","United KingDom","17","Ap #232-2031 Nascetur St.","mauris@yahoO.com","Nathan JeffErson","1-994-348-2483"),
  (5,"non LEo. VIVamus nibh dolor, nonummy ac, feugiat non, lobortis","3645 VJ","DOlnośląskiE","Brazil","11","265-315 Sem, St.","dui@protonmaiL.edu","Tatum Noel","(588) 281-1668"),
  (3,"tempor Erat NEque non quam. Pellentesque habitant morbi tristique senectus","69873","Arica y ParinAcota","Belgium","19","422-538 Nunc Ave","fringilla.purUs@google.com","Vivian Powell","1-446-653-6488"),
  (1,"nascetUR riDICulus mus. Aenean eget magna. Suspendisse tristique neque venenatis","R7P 6L1","SouTh Island","Italy","7","2137 IpsuM AvEnue","curabitur.masSa.vestibulum@yahoo.couk","Ginger Odom","(811) 970-9759"),
  (1,"arcu. VEstiBULum ante ipsum primis in faucibus orci luctus et","73-700","AragÓn","IrelAnd","19","Ap #295-1725 MOlestie St.","duis.ac@aol.neT","Christen Hunt","1-546-623-4314"),
  (8,"pellentESque MAssa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper,","5426 PO","Thừa Thiên–Huế","Singapore","19","Ap #814-9694 CurSus, Rd.","ut@outlook.org","LysaNdra Harmon","(485) 255-2821"),
  (0,"Cras vulputate VeliT Eu sem. Pellentesque ut ipsum ac mi","34671","Antofagasta","Ireland","15","4047 NUllam St.","risUs.quisque@protonmAil.ca","Gemma Fuller","(492) 788-1575"),
  (3,"Nunc lectus peDE, uLTRices a, auctor non, feugiat nec, diam.","3317","Osun","Canada","9","AP #831-5060 Non Ave","ornare.in@yahoo.org","Justina Blanchard","(658) 524-3773"),
  (6,"Vivamus nibh dOLor, NOnummy ac, feugiat non, lobortis quis, pede.","2638","Central Region","IndoNesia","15","Ap #628-5952 SocIis RD.","ipsum@google.edu","GeOrgia Kelley","(653) 185-3765"),
  (9,"enim. Mauris qUIs tURPis vitae purus gravida sagittis. Duis gravida.","37785","North Region","BelgiuM","11","2983 A Street","OrnarE.egestas.ligula@outlook.net","Lacy Gillespie","(543) 721-5071"),
  (7,"augue ac ipsum. PhaSELlus vitae mauris sit amet lorem semper","8127","Punjab","NetheRlands","11","Ap #440-9686 NatOque Rd.","luctus.aliquet@hotmaiL.couk","Harlan Boyle","1-206-877-2938"),
  (3,"hendrerit. DonEC poRTTitor tellus non magna. Nam ligula elit, pretium","11138","Northern TerrItory","Ukraine","3","Ap #638-9445 VeliT St.","erat.nonummy@outlook.Edu","Tatiana Gray","1-685-264-5539"),
  (1,"consectetuer rHOncuS. Nullam velit dui, semper et, lacinia vitae, sodales","3461 RP","Jharkhand","Mexico","3","3092 LigUla. Av.","elIt@aol.com","Hamish Rollins","1-154-718-6657"),
  (2,"est ac facilisIS faCILisis, magna tellus faucibus leo, in lobortis","46481","Drenthe","UkrAine","3","219-5918 Mauris ROad","placerat.orci@hotmail.com","Victor Hopkins","(353) 994-2153"),
  (9,"enim. Etiam grAVida MOlestie arcu. Sed eu nibh vulputate mauris","554665","Leinster","CHina","11","Ap #196-6880 MetUs AvE","neque@icloud.net","LoIs Randall","(584) 585-1064"),
  (9,"lectus rutrum URna, NEc luctus felis purus ac tellus. Suspendisse","065832","Xīnán","FranCe","7","Ap #140-8977 Erat. Av.","massa.quisque@google.neT","Rowan Weiss","1-200-586-3554");
INSERT INTO `myTable` (`nUMBERRaNGE`,`text`,`poStalZip`,`regiOn`,`coUntry`,`list`,`addresS`,`email`,`name`,`phone`)
VALUES
  (5,"feLis ullaMcORPER vivERRa. Maecenas iaculis aliquet diam. Sed diam lorem,","296245","Midi-Pyrénées","Spain","13","Ap #121-3755 Nulla ST.","Nunc@aol.couk","Bruno SchWartz","1-694-633-5650"),
  (5,"SUspendisse non leO. ViVAMus nibh dolor, nonummy ac, feugiat non,","8329","Free State","GermaNy","17","P.O. Box 185, 9794 AUgue Avenue","libero.mauris@aol.net","RAhim Stafford","1-435-337-2943"),
  (4,"pLacerat, augue. SED moLEStie. Sed id risus quis diam luctus","5451","Provence-Alpes-CôtE d'AzuR","Spain","5","P.O. Box 539, 5532 NunC Rd.","metus.in@protonmail.net","Blake Fuller","(331) 462-7458"),
  (8,"ac ipsum. Phasellus VitaE Mauris sit amet lorem semper auctor.","2546","Sverdlovsk Oblast","PhilipPines","15","110-3206 Feugiat Rd.","fusCe.mollis@protonmail.coUk","Vernon Bradshaw","(408) 313-2637"),
  (4,"peDe ac urna. Ut tiNCiduNT vehicula risus. Nulla eget metus","40103","Rajasthan","Costa Rica","3","P.O. Box 117, 5782 PhaRetrA Av.","quis.accumsan@hotmail.couk","Carson Higgins","(605) 931-3398"),
  (7,"faCilisis. SuspendiSSe cOMModo tincidunt nibh. Phasellus nulla. Integer vulputate, risus","LP3 2IU","Jigawa","China","5","936-9143 Ut Av.","nisl@gooGle.net","Hop BarnEs","1-500-715-7357"),
  (8,"moNtes, nascetur riDIculUS mus. Aenean eget magna. Suspendisse tristique neque","9414","Leinster","Chile","11","Ap #759-3428 Ligula. Rd.","cursus.luctus.ipsum@protonMail.net","Charles Melendez","(530) 254-5374"),
  (4,"quAm. Curabitur vel LectUS. Cum sociis natoque penatibus et magnis","652521","Hậu Giang","IrelaNd","17","Ap #451-2901 Nulla. Ave","a@Yahoo.ca","Jin Hancock","1-683-444-3666"),
  (6,"loreM lorem, luctus uT, peLLEntesque eget, dictum placerat, augue. Sed","36057","Tula Oblast","Peru","11","P.O. Box 243, 5163 OrnaRe RoAd","etiam.imperdiet.dictum@protoNmail.com","Henry Ward","(587) 128-0445"),
  (3,"veliT eget laoreet poSUere, Enim nisl elementum purus, accumsan interdum","27371","Jalisco","Mexico","19","910-3817 PorttItor Rd.","ipsUm.nunc.id@protonmail.edu","Simone Dawson","(273) 666-1123"),
  (5,"VivaMus sit amet risuS. DoNEC egestas. Aliquam nec enim. Nunc","31C 0S3","Namen","Pakistan","5","222-6132 LoreM Rd.","purUs.mAecenas@icloud.net","Blythe Gamble","(651) 275-4526"),
  (1,"ut, Nulla. Cras eu teLLus EU augue porttitor interdum. Sed","62940","Nordland","South KorEa","13","5213 JustO Av.","amet.uLtricIes@aol.org","RajA Patterson","1-868-826-3614"),
  (4,"vestIbulum lorem, sit Amet ULtricies sem magna nec quam. Curabitur","23638","Sơn La","Poland","13","988-5985 AccumsAn Avenue","arCu.vestibulum@aol.net","RobIn Delgado","(732) 785-9248"),
  (4,"justo. Praesent luctus. CurABItur egestas nunc sed libero. Proin sed","36574","Møre og Romsdal","UniTed StatEs","1","375-5585 AEnean Street","lEo@hOtmail.edu","Daniel PowerS","(985) 495-7685"),
  (3,"In sceLerisque scelerisQUe dUI. Suspendisse ac metus vitae velit egestas","13495","Lambayeque","Australia","9","149-5152 MauriS Street","sEd@iCloud.edu","Abdul Madden","(827) 554-7558"),
  (5,"Nam nuLla magna, malesuADa vEL, convallis in, cursus et, eros.","60613","West Region","United KIngdom","9","Ap #254-5970 Curae Avenue","nuNc.sit@outlook.org","Leandra Henderson","(217) 176-3343"),
  (5,"ac risUs. Morbi metus. VIvamUS euismod urna. Nullam lobortis quam","735332","Puntarenas","Russian FederatioN","9","Ap #131-8908 Dolor St.","nAtoqUe.penatibus.et@icloud.coM","Margaret Joyce","(845) 521-6886"),
  (7,"MaecenAs libero est, coNGue A, aliquet vel, vulputate eu, odio.","1876-4963","Innlandet","VietnaM","17","191-6470 Nam StReet","friNgillA.purus@outlook.couk","Bryar Henry","(864) 831-8656"),
  (6,"id nunC interdum feugiaT. SeD Nec metus facilisis lorem tristique","4151-8191","Oklahoma","Turkey","11","Ap #737-2675 Et St.","malEsuadA.vel@outlook.ca","FreYa Brady","(495) 176-5787"),
  (5,"eu, plAcerat eget, veneNAtis A, magna. Lorem ipsum dolor sit","38517","Brussels HoofdstedelijK Gewest","United Kingdom","5","Ap #129-3218 Orci, Avenue","laCinia.sed@google.com","Ocean Jimenez","1-252-127-3233"),
  (8,"cursus in, hendrerit coNSectETUer, cursus et, magna. Praesent interdum ligula","117099","Zhōngnán","Vietnam","19","Ap #191-2571 TellUs. Rd.","Amet.Luctus.vulputate@aol.ca","JUdith Maddox","(414) 341-6626"),
  (3,"ornare, Lectus ante dictuM mi, AC mattis velit justo nec","58281","Bourgogne","Mexico","19","8018 AUgue St.","aT.libero@GooglE.com","Jackson GIllespie","1-731-476-3411"),
  (6,"morbi trIstique senectus ET neTUS et malesuada fames ac turpis","30001","Orenburg Oblast","Italy","7","606-1014 Ultricies STreet","AuctOr@google.org","Uma Romero","1-208-227-2385"),
  (9,"urna. NuLlam lobortis quaM a fELIs ullamcorper viverra. Maecenas iaculis","42447","Kyiv oblast","Austria","5","783-6022 In Av.","Molestie.tOrtoR@yahoo.com","LestEr Berger","1-202-663-6123"),
  (2,"Vivamus Non lorem vitae oDIo sAGIttis semper. Nam tempor diam","560497","Cordillera AdministratiVe Region","Costa Rica","3","3382 Lobortis RD.","mi.felis.adiPiscing@hotmail.couk","Rashad Burke","1-951-757-4847"),
  (2,"hendreriT id, ante. Nunc MAuriS Sapien, cursus in, hendrerit consectetuer,","67668","West Nusa Tenggara","SweDen","13","Ap #249-5473 Etiam Street","lectUs.ante@yahoo.edu","Abbot DeLgado","1-528-619-3574"),
  (4,"sem egesTas blandit. Nam NUlla MAgna, malesuada vel, convallis in,","57-63","Schleswig-Holstein","PhiLippines","9","3259 Enim. Rd.","ad.litora.tOrquEnt@google.net","Seth Barry","(253) 258-8448"),
  (9,"nunc id Enim. Curabitur mASsa. VEstibulum accumsan neque et nunc.","1588-6368","Munster","Brazil","15","560-9466 Et, Road","sed.facIlisiS.vitae@yahoo.net","Jemima Rollins","(246) 488-6482"),
  (4,"scelerisQue scelerisque dUI. SUSPendisse ac metus vitae velit egestas lacinia.","3287","Kujawsko-pomorskie","BrazIl","3","Ap #878-3280 Sed AvEnue","suSpenDisse.dui@aol.net","CherokEe Dillon","1-956-747-6662"),
  (5,"eget magNa. Suspendisse tRIstiQUE neque venenatis lacus. Etiam bibendum fermentum","8862","Southeast Sulawesi","GermAny","1","772-8717 Accumsan Street","iD.moLlis@protonmail.edu","Malik Foley","1-249-208-1181");
INSERT INTO `mYTable` (`numberrAngE`,`TExT`,`postalZip`,`region`,`counTry`,`lIst`,`addresS`,`email`,`name`,`Phone`)
VALUES
  (7,"nunc nulla VulputatE DUI, Nec TEMpus mauris erat eget ipsum.","8028","Huádōng","Nigeria","15","700-5439 Porta Road","a@yahoo.com","Uriah Finley","(876) 577-3148"),
  (2,"rutrum non, hendrerit id, aNTe. NUNc mauris sapien, cursus in,","32185","Western Cape","Belgium","17","Ap #865-1497 Ut Av.","tellus.Id@aoL.couk","Quamar EnglisH","1-532-362-0176"),
  (2,"non dui neC urna suscipit nONummY. Fusce fermentum fermentum arcu.","5162","West Region","Costa Rica","13","Ap #599-2022 EroS. Rd.","scelErisqUe@google.net","Ainsley MCclain","1-248-349-3789"),
  (4,"tortor at Risus. Nunc ac seM ut DOLor dapibus gravida.","978776","Nordland","Spain","9","438-1776 VeStibulum StReet","eRat.Etiam.vestibulum@yahoo.net","Randall Burton","(455) 623-6831"),
  (6,"Cras lorem lorem, luctus ut, pelLENtesque eget, dictum placerat, augue.","198614","Central Region","India","11","P.O. Box 544, 7123 CuRabitur St.","bibendum.ullamcorper@aol.org","SilAs Greene","(211) 202-0451"),
  (4,"massa rutrUm magna. Cras coNVallIS convallis dolor. Quisque tincidunt pede","555440","Waals-Brabant","Mexico","9","Ap #218-6722 Eu AvenuE","ante@ProtOnmail.edu","Fritz DelaneY","1-878-787-7168"),
  (1,"et ultriceS posuere cubilia CuraE Phasellus ornare. Fusce mollis. Duis","67312-605","Free State","Chile","11","414-8704 Proin Rd.","Mauris.sUspenDisse@icloud.com","AlIka Ware","1-956-162-5330"),
  (5,"sociis natOque penatibus et MagnIS dis parturient montes, nascetur ridiculus","3772","Sardegna","France","3","804-5246 NAscetur StrEet","egeStas@aol.org","Willow Hood","(357) 353-3703"),
  (0,"posuere at, velit. Cras lorEM loREM, luctus ut, pellentesque eget,","9811","Cherkasy oblast","Nigeria","3","400-8818 Mi. Rd.","aC.nulla@hoTmaiL.com","Lucius Hall","1-353-730-2793"),
  (2,"ligula. DoNec luctus aliqueT odiO. Etiam ligula tortor, dictum eu,","234161","Lombardia","Canada","3","Ap #667-4982 Orci RoaD","suspeNdisSe.tristique@aol.ca","DebRa Evans","1-514-456-7798"),
  (2,"Nullam velIt dui, semper et, lacINIa vitae, sodales at, velit.","4203-1262","Limousin","Russian FedEration","7","Ap #397-1315 Enim. St.","mauriS@goOgle.net","Beverly Malone","1-377-566-3793"),
  (3,"adipiscing fringilla, porttITor VULputate, posuere vulputate, lacus. Cras interdum. Nunc","3353","Galicia","Ukraine","11","5595 Sed St.","frinGilla.portTitor@yahoo.couk","AUgust Casey","1-641-935-3607"),
  (10,"ipsum. CuRabitur consequat, lecTUS sit amet luctus vulputate, nisi sem","6747-3202","Azad Kashmir","Sweden","11","894-5426 Congue Road","massa.VestiBulum@aol.org","Xavier Larsen","1-872-542-2632"),
  (6,"ante ipsum primis in faucibUS orCI luctus et ultrices posuere","7136","Punjab","Singapore","9","P.O. Box 443, 3723 Vel Road","VeliT.aliquam@protonmail.couk","HaMilton Whitaker","(428) 329-7251"),
  (10,"pede. PraEsent eu dui. Cum SociIS Natoque penatibus et magnis","9789","Mpumalanga","Italy","7","Ap #219-9368 Sem Road","semper.telLus.id@aol.edu","Jonas SImpson","(628) 480-3431"),
  (2,"id, libero. Donec consectetUEr mAURis id sapien. Cras dolor dolor,","03284","Delaware","Costa Rica","11","946-9204 Donec AVenue","et.erOs@ouTlook.org","Palmer AnderSon","(624) 329-0116"),
  (7,"massa non Ante bibendum ullAMcorPER. Duis cursus, diam at pretium","383954","Pernambuco","Canada","7","Ap #211-5118 Nec St.","quisque.libEro@yahoo.edu","Rae CroSby","(415) 871-4154"),
  (6,"Nunc mauriS. Morbi non sapiEN moLEStie orci tincidunt adipiscing. Mauris","586455","Henegouwen","Chile","13","P.O. Box 198, 3338 AcCumsan RD.","Mauris.blandit.mattis@protonmail.eDu","Sonya Deleon","1-687-785-5858"),
  (10,"Sed auctoR odio a purus. DUIs eLEMEntum, dui quis accumsan","45482-75788","North Chungcheong","Nigeria","9","P.O. Box 895, 1091 DIctum AvenUe","viverra.donec@hotmail.com","FletchEr Potts","1-305-511-4862"),
  (1,"Duis digniSsim tempor arcu. VestIBUlum ut eros non enim commodo","54374","Northern Territory","Peru","17","601-8990 Leo. St.","ipSum.curSus@oUtlook.org","Kelly WEst","(125) 405-5123");
-- 1
SELECT postalZip AS codigoPostal,
	region AS región,
    country AS país
FROM myTable;
-- 2
SELECT * FROM myTable WHERE phone LIKE '(811)%';
-- 3
SELECT * FROM myTable WHERE country IN ('Italy', 'Spain');
-- 4
SELECT COUNT(*) FROM myTable;
-- 5
SELECT region, country, postalZip FROM myTable WHERE id IN 
	(SELECT id FROM myTable WHERE country IN ('Germany', 'Turkey'));
-- 6
SELECT MAX(id), MIN(id) FROM myTable;
-- 7
SELECT COUNT(*), country FROM myTable GROUP BY (country);
-- 8
SELECT * FROM myTable ORDER BY postalZip LIMIT 10;
-- 9
DELETE FROM myTable WHERE country = 'Singapore';
SELECT * FROM myTable WHERE country = 'Singapore';
-- 10
UPDATE myTable SET country = 'España' WHERE country = 'Spain';
SELECT * FROM myTable WHERE country = 'España';