DROP DATABASE IF EXISTS SQL05;
CREATE DATABASE IF NOT EXISTS SQL05;
USE SQL05;

CREATE TABLE IF NOT EXISTS ALBUM (
	IDALBUM INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ALBUMNAME VARCHAR(255) NOT NULL,
    DATERELEASE DATE
);

CREATE TABLE IF NOT EXISTS ARTIST (
    IDARTIST INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ARTISTNAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENRE (
	IDGENRE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    GENRE VARCHAR(255) NOT NULL
);

INSERT INTO SQL05.ALBUM VALUES
	(NULL, 'Thriller', '1982-11-30'),
    (NULL, 'Back in Black', '1980-07-25'),
    (NULL, 'The Bodyguard', '1992-11-17'),
    (NULL, 'The Dark Side of the Moon', '1973-03-01'),
    (NULL, 'Saturday Night Fever', '1977-11-15');

INSERT INTO SQL05.ARTIST VALUES
	(NULL, 'Michael Jackson'),
    (NULL, 'AC/DC'),
    (NULL, 'Whitney Houston'),
    (NULL, 'Pink Floyd'),
    (NULL, 'Bee Gees');
    
INSERT INTO SQL05.GENRE VALUES
	(NULL, 'Pop'),
    (NULL, 'Hard rock'),
    (NULL, 'R&B'),
    (NULL, 'Rock'),
    (NULL, 'Disco');

SELECT * FROM SQL05.ALBUM; 
SELECT * FROM SQL05.ARTIST;    
SELECT * FROM SQL05.GENRE;
       