DROP DATABASE IF EXISTS SQL05;
CREATE DATABASE IF NOT EXISTS SQL05;
USE SQL05;

CREATE TABLE IF NOT EXISTS ALBUM (
	IDALBUM INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ALBUMNAME VARCHAR(255) NOT NULL,
    DATERELEASE DATETIME
);

CREATE TABLE IF NOT EXISTS ARTIST (
	IDARTIST INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ARTISTNAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENRE (
	IDGENRE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    GENRE VARCHAR(255) NOT NULL
);

DESCRIBE SQL05.ALBUM;